### ISSUE TITLE
Add option to disable proposer duty polling after epoch

### ISSUE THREAD

**Issue by dapplion** [pk910/light-beaconchain-explorer#10]
### Background

Whisk SSLE (Single Secret Leader Election) is a new Ethereum protocol feature being tested now. (ref: https://ethresear.ch/t/whisk-a-practical-shuffle-based-ssle-protocol-for-ethereum/11763)

The point of the feature is to identity of the next proposer private until its block is published. This means:
- proposer duties cannot be known in advance
- if there is a missed slot it will never be known how missed the slot

@parithosh has deployed a testnet for whisk https://github.com/ethpandaops/whisk-testnets/ with this explorer. BTW great work on the explorer, love it so far! :heart: 

However the explorer stalls indexing at the Whisk fork epoch since it cannot poll duties. More precisely, the beacon node returns an error to calls to `eth/v1/validator/duties/proposer/` since it cannot serve that data.

```
INFO[0008] synchronizing epoch 0                         module=synchronizer
WARN[0008] could not lazy load proposer duties for epoch 1501: error retrieving proposer duties: url: http://localhost:5052/eth/v1/validator/duties/proposer/1501, error-response: {"code":500,"message":"UNHANDLED_ERROR: BeaconStateError(NoProposerShuffleAfterWhisk)","stacktraces":[]}  client=default module=indexer
WARN[0008] could not find proposer duties for epoch 1501  client=default module=indexer
WARN[0008] could not lazy load proposer duties for epoch 1503: error retrieving proposer duties: url: http://localhost:5052/eth/v1/validator/duties/proposer/1503, error-response: {"code":500,"message":"UNHANDLED_ERROR: BeaconStateError(NoProposerShuffleAfterWhisk)","stacktraces":[]}  client=default module=indexer
WARN[0008] could not find proposer duties for epoch 1503  client=default module=indexer
WARN[0008] could not lazy load proposer duties for epoch 1502: error retrieving proposer duties: url: http://localhost:5052/eth/v1/validator/duties/proposer/1502, error-response: {"code":500,"message":"UNHANDLED_ERROR: BeaconStateError(NoProposerShuffleAfterWhisk)","stacktraces":[]}  client=default module=indexer
WARN[0008] could not find proposer duties for epoch 1502  client=default module=indexer
INFO[0010] received block 1503:48117 [0x6a322ff15c787ce63c92a0c062f4ce462263cb8d58737e7829bc25d40ca88473] stream  client=default module=indexer
INFO[0015] index page called  
```

It would be great to have this explorer be compatible with Whisk for ease of debugging on devnets and to start iterating on how explorers would deal with post-whisk world with proposer privacy.

Please let me know what ideas you have to deal with case, I will suggest some ideas below

### Suggested solution A (minimal)

Add a config value `whisk_epoch` after which the indexer fills the proposer duties response with dummy values (i.e. the 0 validator). This won't require any changes to the UI, API, etc and should allow to continue indexing

### Suggested solution B (full)

Add a config value `whisk_epoch` after which indexer changes the render of proposer duties.
1. The author of the block can be shown only for non-missed blocks and should be read from the block.proposer_index
2. For missed slots, do not display any index but some tag like "unknown"
3. On the epoch view, list proposers only of already seen blocks, following points 1 and 2

**Comment by pk910** [comment]
Heya @dapplion,
Thanks for your suggestions, I'll gonna make it whisk ready :)
Would you mind giving me access to a whisk RPC node for development?

**Comment by parithosh** [comment]
I've added access for you here: https://github.com/ethpandaops/whisk-testnets
You can ssh port forward the required ports and interact with it. We have nginx setup, but the DNS settings aren't done yet.

**Comment by pk910** [comment]
Implemented whisk support :)

It needs to be configured as follows:
```
...

chain:
  configPath: "https://raw.githubusercontent.com/ethpandaops/whisk-testnets/master/network-configs/whisk-testnet-0/config.yaml"
  whiskForkEpoch: 0

...
```

Starting from epoch `whiskForkEpoch`, the explorer will no longer poll for proposer duties.
The indexer fills up the proposer duties with a placeholder value (`9223372036854775807`), which is displayed as "unknown" in the UI.

You'll need to run one of your nodes in archive mode (with `--slots-per-restore-point 32` on lighthouse) and use that as the explorer endpoint.
Otherwise the explorer will be terrible slow or even fails with "deadline exceeded" errors when browsing certain pages.

**Comment by pk910** [comment]
I've noticed a small issue:
https://beaconlite.whisk-testnet-0.ethpandaops.io/validator/9438/slots

That page should show all blocks that were proposed by 9438, but it currently only shows proposals from indexer cache.
The view uses the assignments table as datasource, so it's not really a surprise that all block proposals are now shown under the unknown placeholder index:
https://beaconlite.whisk-testnet-0.ethpandaops.io/validator/9223372036854775807/slots

**Comment by pk910** [comment]
I'm closing this as the explorer seems to be working fine on whisk-testnet0 :)
Thanks again for your detailed request.
